// Dados mockados (não há backend): etapas do fluxo, perfis de usuário,
// módulos de permissão e a base de dados inicial (seed) de OS, estoque,
// clientes, usuários, auditoria e notificações.
const stages = [
  "Recepção / Check-in",
  "Em Diagnóstico",
  "Aguardando Aprovação",
  "Aguardando Início",
  "Em Execução",
  "Aguardando Peças",
  "Controle de Qualidade",
  "Pronto para Entrega",
];

const roles = {
  gerente: ["Cristina Ferraz", "Gerente / Dona", "CF", "avatar-blue"],
  mecanico: ["Marcos Andrade", "Mecânico / Funileiro", "MA", "avatar-green"],
  cliente: ["Eduardo Ramos", "Cliente", "ER", "avatar-orange"],
  admin: ["Paula Menezes", "Administradora", "PM", "avatar-purple"],
};

const permModules = [
  ["dashboard", "Visão geral"],
  ["kanban", "Kanban"],
  ["orders", "Ordens de serviço"],
  ["clients", "Clientes e veículos"],
  ["stock", "Estoque"],
  ["reports", "Indicadores"],
  ["notifications", "Notificações"],
  ["portal", "Portal do cliente"],
  ["users", "Usuários"],
  ["audit", "Auditoria"],
  ["settings", "Configurações"],
];

const seed = {
  orders: [
    {
      id: "OS-1048",
      plate: "QWE-4A21",
      car: "Honda Civic 2021",
      client: "Eduardo Ramos",
      problem: "Colisão dianteira: para-choque, capô e paralama.",
      stage: 6,
      value: 4820,
      days: 3,
      owner: "MA",
      approved: true,
      reserved: true,
      progress: 92,
      parts: [
        ["Massa plástica", 2],
        ["Lixa P800", 4],
      ],
      check: [1, 1, 1, 1, 0],
      photos: 5,
    },
    {
      id: "OS-1049",
      plate: "ABC-1D23",
      car: "Toyota Corolla 2020",
      client: "Ana Beatriz",
      problem: "Risco profundo e amassado na porta traseira.",
      stage: 2,
      value: 1950,
      days: 1,
      owner: "MA",
      approved: false,
      reserved: false,
      progress: 30,
      parts: [["Verniz PU Alto Sólidos", 1]],
      check: [0, 0, 0, 0, 0],
      photos: 2,
    },
    {
      id: "OS-1050",
      plate: "KLM-9P80",
      car: "VW T-Cross 2023",
      client: "Rafael Souza",
      problem: "Reparo estrutural lateral e pintura.",
      stage: 4,
      value: 7350,
      days: 4,
      owner: "MA",
      approved: true,
      reserved: true,
      progress: 54,
      parts: [
        ["Primer PU", 2],
        ["Catalisador", 1],
      ],
      check: [0, 0, 0, 0, 0],
      photos: 6,
    },
    {
      id: "OS-1051",
      plate: "HJK-7B62",
      car: "Chevrolet Onix 2022",
      client: "Juliana Costa",
      problem: "Pintura do teto e correção de acabamento.",
      stage: 1,
      value: 0,
      days: 0,
      owner: "MA",
      approved: false,
      reserved: false,
      progress: 10,
      parts: [["Lixa P800", 2]],
      check: [0, 0, 0, 0, 0],
      photos: 1,
    },
    {
      id: "OS-1044",
      plate: "ABC-1D23",
      car: "Toyota Corolla 2020",
      client: "Ana Beatriz",
      problem: "Reparo de paralama e pintura localizada.",
      stage: 7,
      value: 3250,
      days: 7,
      owner: "MA",
      approved: true,
      reserved: true,
      progress: 100,
      parts: [["Primer PU", 1]],
      check: [1, 1, 1, 1, 1],
      photos: 8,
    },
    {
      id: "OS-1041",
      plate: "KLM-9P80",
      car: "VW T-Cross 2023",
      client: "Rafael Souza",
      problem: "Funilaria de porta e pintura.",
      stage: 3,
      value: 4100,
      days: 6,
      owner: "MA",
      approved: true,
      reserved: true,
      progress: 46,
      parts: [
        ["Massa plástica", 1],
        ["Verniz PU Alto Sólidos", 1],
      ],
      check: [0, 0, 0, 0, 0],
      photos: 4,
    },
  ],
  stock: [
    ["Tinta PU Branco", "TIN-001", 18, 10, "L"],
    ["Primer PU", "TIN-014", 7, 8, "L"],
    ["Massa plástica", "MAT-022", 26, 12, "kg"],
    ["Lixa P800", "ABR-008", 32, 20, "un"],
    ["Lixa P1200", "ABR-011", 9, 15, "un"],
    ["Parachoque Civic 2020", "PC-104", 1, 2, "un"],
    ["Farol T-Cross D", "FR-221", 4, 2, "un"],
    ["Verniz PU Alto Sólidos", "TIN-031", 5, 6, "L"],
    ["Catalisador", "TIN-044", 14, 6, "L"],
  ],
  clients: [
    ["Eduardo Ramos", "(79) 99911-2233", "eduardo@email.demo", "QWE-4A21", "Honda Civic 2021"],
    ["Ana Beatriz", "(79) 99821-4470", "ana@email.demo", "ABC-1D23", "Toyota Corolla 2020"],
    ["Rafael Souza", "(79) 99122-7831", "rafael@email.demo", "KLM-9P80", "VW T-Cross 2023"],
    ["Juliana Costa", "(79) 99712-1190", "juliana@email.demo", "HJK-7B62", "Chevrolet Onix 2022"],
  ],
  users: [
    [
      "Cristina Ferraz",
      "Gerente / Dona",
      "gerente",
      "CF",
      1,
      {
        dashboard: 1,
        kanban: 1,
        orders: 1,
        clients: 1,
        stock: 1,
        reports: 1,
        notifications: 1,
        portal: 0,
        users: 0,
        audit: 0,
        settings: 1,
      },
    ],
    [
      "Marcos Andrade",
      "Mecânico / Funileiro",
      "mecanico",
      "MA",
      1,
      {
        dashboard: 1,
        kanban: 1,
        orders: 1,
        clients: 1,
        stock: 1,
        reports: 0,
        notifications: 1,
        portal: 0,
        users: 0,
        audit: 0,
        settings: 0,
      },
    ],
    [
      "Eduardo Ramos",
      "Cliente",
      "cliente",
      "ER",
      1,
      {
        dashboard: 0,
        kanban: 0,
        orders: 0,
        clients: 0,
        stock: 0,
        reports: 0,
        notifications: 1,
        portal: 1,
        users: 0,
        audit: 0,
        settings: 0,
      },
    ],
    [
      "Paula Menezes",
      "Administradora",
      "admin",
      "PM",
      1,
      {
        dashboard: 1,
        kanban: 1,
        orders: 1,
        clients: 1,
        stock: 1,
        reports: 1,
        notifications: 1,
        portal: 0,
        users: 1,
        audit: 1,
        settings: 1,
      },
    ],
  ],
  audit: [
    [
      "04/09/2026 11:42",
      "Cristina Ferraz",
      "Bloqueio de transição",
      "OS-1049",
      "Orçamento ainda aguardando decisão.",
    ],
    ["04/09/2026 10:58", "Marcos Andrade", "Atualização", "OS-1048", "Checklist 4/5 itens."],
    [
      "04/09/2026 10:15",
      "Paula Menezes",
      "Alteração administrativa",
      "Usuário #3",
      "Permissões mantidas.",
    ],
    ["04/09/2026 09:30", "Cristina Ferraz", "Reserva de peças", "OS-1050", "2 itens reservados."],
  ],
  notifications: [
    [
      "Orçamento pendente",
      "OS-1049 aguarda decisão do cliente.",
      "Há 24 min",
      "amber",
      0,
      { view: "orders", orderId: "OS-1049" },
    ],
    [
      "Estoque crítico",
      "Primer PU abaixo do ponto de reposição.",
      "Há 1 h",
      "red",
      0,
      { view: "stock" },
    ],
    [
      "Veículo pronto",
      "OS-1044 passou no controle de qualidade.",
      "Há 2 h",
      "green",
      0,
      { view: "orders", orderId: "OS-1044" },
    ],
    [
      "Execução iniciada",
      "OS-1050 entrou em execução.",
      "ontem",
      "blue",
      0,
      { view: "orders", orderId: "OS-1050" },
    ],
  ],
};
